name: "Test Call - Secret"
on:
  workflow_dispatch

jobs:
  test_call:
    steps:
      - name: "Check Token"
        run: |
          if (${{ secrets.TOKEN }} -eq "T3stT0k3nV4lu3"){
            echo "TOken value is correct!"
          }          
        shell: pwsh
