name: "Main Call Test"
on:
  workflow_dispatch

jobs:
  call1:
    uses: lyb-rozgaar/test-workflow/.github/workflows/subcall1.yml@main
    with:
      token1: ${{secrets.TOKEN}}
  call2:
    needs: call1
    uses: lyb-rozgaar/test-workflow/.github/workflows/subcall2.yml@main
    
